seed: 42
project_name: "my_project"
run_name: ${now:%Y-%m-%d_%H-%M-%S}

data:
  mean: [0.1307]
  std: [0.3081]
  num_workers: 4

model:
  input_dim: 784  # 28 * 28
  hidden_dim: 128  # This should match the output of fc1
  output_dim: 10  # Number of classes in MNIST
  dropout: 0.5

training:
  epochs: 40
  batch_size: 32
  lr: 0.001
  use_gpu: true
  use_amp: true
  accumulate_grad_batches: 1
  patience: 10

paths:
  data_dir: "../../data/"
  output_dir: "outputs/"
  log_dir: "logs/"
  checkpoint_dir: "checkpoints/"

hydra:
  run:
    dir: ${paths.output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
